### ISSUE TITLE
Creating Slab From Scratch Doesn't Resolve Tile NGuids Correctly.

### ISSUE THREAD

**Issue by LordAshes** [svenboulanger/TaleSpire.Slab#1]
I have create code that generates a slab from scratch which has multiple different tile assets. To get the tile NGuids, I dropped a single tile in Talespire, and then used this library to parse the slab information to get the NGuid.
I am using the following code to create TaleSpire.Slab.NGuids based on the strings that I read from the library:

``
new TaleSpire.Slab.NGuid(System.Guid.Parse("e62c6746-cecf-46bf-20d2-0000000020d2"))  
``

I have read my SlabCode string back, using this library, to verify that the NGuid were actually set and the results show the different NGuids in the slab.

However, when I paste the code into Talespire, all of the tiles show up as cube tiles with "X" on each side.

**Comment by LordAshes** [comment]
Here is the code that I am using to build the SlabCode:

```
            List<Layout> layouts = new List<Layout>();
            foreach (KeyValuePair<string,List<Node>> tile in  nodesByTiles)
            {
                Console.WriteLine("Writing "+tile.Key+" Tiles... ("+ tileGuids[tile.Key]+")");
                float rot = tileRotations[tile.Key];
                var layoutHeader = new LayoutData(tileGuids[tile.Key], (ushort)tile.Value.Count);
                var layout = new Layout(layoutHeader);
                for(int t=0; t<tile.Value.Count; t++)
                {
                    TaleSpire.Slab.Float3 pos = new TaleSpire.Slab.Float3((float)tile.Value.ElementAt(t).GetPosition().x, (tile.Key == "#") ? 0.75f : 0f, (float)tile.Value.ElementAt(t).GetPosition().y);
                    ExtraBits eb = new ExtraBits();
                    layout.Assets[t] = new AssetData(pos, rot, eb);
                }
                layouts.Add(layout);
            }
            Console.WriteLine("SlabCode Set To Clipboard");
            TaleSpire.Slab.V2.Slab slab = new TaleSpire.Slab.V2.Slab(layouts.ToArray());
            System.Windows.Forms.Clipboard.SetText(slab.Export());
```

**Comment by LordAshes** [comment]
![image](https://github.com/svenboulanger/TaleSpire.Slab/assets/27384952/d3fbc6b9-0f75-45a6-9e98-d88db5bb8039)

**Comment by svenboulanger** [comment]
Hey there! I found some time to spend on this here.

Thanks to your debugging I found that problem is actually in the parsing of the Guid. It is incorrectly converting a Guid to an NGuid... I was a bit sidetrackked as the GZIP leads to different results even though the uncompressed bytes are exactly the same.

I'll fix it right now :-)
